In [1]:
import pandas as pd

df = pd.read_parquet(
    "../data/processed/papers.parquet"
)

print("Shape:", df.shape)

Shape: (944, 15)

In [2]:
pd.set_option("display.max_colwidth", 150)

df[
    ["title", "year", "citation_count"]
].sort_values(
    "citation_count",
    ascending=False
).head(50)

,title,year,citation_count
424,SciPy 1.0: fundamental algorithms for scientific computing in Python,2020,39949
385,Large language models encode clinical knowledge,2023,3909
403,"Pre-train, Prompt, and Predict: A Systematic Survey of Prompting Methods in Natural Language Processing",2022,3868
388,Dense Passage Retrieval for Open-Domain Question Answering,2020,3352
159,Affordance-Compiled Intelligence: Observable-Only Cognitive Impedance Matching for No-Meta LLM-Integrated Systems,2020,3066
390,Behavioral Safety and Context Retention of Large Language Models in a Longitudinal ICU Simulation under Offline Conditions,2023,2639
379,"A Survey on Hallucination in Large Language Models: Principles, Taxonomy, Challenges, and Open Questions",2024,2111
399,PaLM: Scaling Language Modeling with Pathways,2022,2096
470,"Natural language processing: state of the art, current trends and challenges",2022,1820
414,A survey on large language model based autonomous agents,2024,1649
201,A Survey of Large Language Models,2026,1537
409,Scaling Laws for Neural Language Models,2020,1513
408,Lost in the Middle: How Language Models Use Long Contexts,2024,1333
427,Recent Advances in Natural Language Processing via Large Pre-trained Language Models: A Survey,2023,1295
445,Making Pre-trained Language Models Better Few-shot Learners,2021,1274
443,AutoPrompt: Eliciting Knowledge from Language Models with Automatically Generated Prompts,2020,1216
439,The future landscape of large language models in medicine,2023,1054
481,"A survey on large language model (LLM) security and privacy: The Good, The Bad, and The Ugly",2024,1045
421,Emergent Abilities of Large Language Models,2022,1013
351,Leveraging Passage Retrieval with Generative Models for Open Domain Question Answering,2021,1009
436,Autonomous chemical research with large language models,2023,1007
450,Toward expert-level medical question answering with large language models,2025,959
460,BLIP-2: Bootstrapping Language-Image Pre-training with Frozen Image Encoders and Large Language Models,2023,917
96,A Survey on RAG Meeting LLMs: Towards Retrieval-Augmented Large Language Models,2024,757
0,Retrieval-Augmented Generation for Large Language Models: A Survey,2023,748
472,Taxonomy of Risks posed by Language Models,2022,706
217,LaMDA: Language Models for Dialog Applications,2022,696
465,Training Compute-Optimal Large Language Models,2022,660
367,REALM: Retrieval-Augmented Language Model Pre-Training,2020,513
2,RAGAs: Automated Evaluation of Retrieval Augmented Generation,2024,487
447,Attention is not all you need: the complicated case of ethically using large language models in healthcare and medicine,2023,482
284,Enriching Location Representation with Detailed Semantic Information,2024,467
1,Active Retrieval Augmented Generation,2023,454
459,Augmenting human innovation teams with artificial intelligence: Exploring transformer‐based language models,2023,434
368,In-Context Retrieval-Augmented Language Models,2023,407
256,Almanac — Retrieval-Augmented Language Models for Clinical Medicine,2024,401
3,Benchmarking Large Language Models in Retrieval-Augmented Generation,2024,382
214,A Comprehensive Overview of Large Language Models,2023,368
6,Improving the Domain Adaptation of Retrieval Augmented Generation (RAG) Models for Open Domain Question Answering,2023,316
252,Current applications and challenges in large language models for patient care: a systematic review,2025,306
235,Large language models for generative information extraction: a survey,2024,286
231,Large Legal Fictions: Profiling Legal Hallucinations in Large Language Models,2024,286
756,Antibodies Targeting the Transferrin Receptor 1 (TfR1) as Direct Anti-cancer Agents,2021,271
4,Benchmarking Retrieval-Augmented Generation for Medicine,2024,269
247,Large Language Models for Mental Health Applications: Systematic Review,2024,259
230,Galactica: A Large Language Model for Science,2022,258
245,Query Rewriting in Retrieval-Augmented Large Language Models,2023,257
242,A review of large language models and autonomous agents in chemistry,2024,250
268,"Large language models in medical and healthcare fields: applications, advances, and challenges",2024,239
276,Siren's Song in the AI Ocean: A Survey on Hallucination in Large Language Models,2023,239

In [3]:
rag_mask = (
    df["title"]
    .fillna("")
    .str.lower()
    .str.contains(
        r"\brag\b|retrieval.?augmented",
        regex=True
    )
)

print(
    "Titles explicitly mentioning RAG:",
    rag_mask.sum()
)

Titles explicitly mentioning RAG: 765

In [4]:
df.loc[
    rag_mask,
    ["title", "year", "citation_count"]
].sort_values(
    "citation_count",
    ascending=False
).head(50)

,title,year,citation_count
96,A Survey on RAG Meeting LLMs: Towards Retrieval-Augmented Large Language Models,2024,757
0,Retrieval-Augmented Generation for Large Language Models: A Survey,2023,748
367,REALM: Retrieval-Augmented Language Model Pre-Training,2020,513
2,RAGAs: Automated Evaluation of Retrieval Augmented Generation,2024,487
1,Active Retrieval Augmented Generation,2023,454
368,In-Context Retrieval-Augmented Language Models,2023,407
256,Almanac — Retrieval-Augmented Language Models for Clinical Medicine,2024,401
3,Benchmarking Large Language Models in Retrieval-Augmented Generation,2024,382
6,Improving the Domain Adaptation of Retrieval Augmented Generation (RAG) Models for Open Domain Question Answering,2023,316
4,Benchmarking Retrieval-Augmented Generation for Medicine,2024,269
245,Query Rewriting in Retrieval-Augmented Large Language Models,2023,257
7,Retrieval augmented generation for large language models in healthcare: A systematic review,2025,232
208,A Survey on RAG with LLMs,2024,229
200,Adaptive-RAG: Learning to Adapt Retrieval-Augmented Large Language Models through Question Complexity,2024,218
215,The Power of Noise: Redefining Retrieval for RAG Systems,2024,210
369,Retrieval Augmented Language Model Pre-Training,2020,208
15,Optimization of hepatological clinical guidelines interpretation by large language models: a retrieval augmented generation-based framework,2024,207
330,Atlas: Few-shot Learning with Retrieval Augmented Language Models,2022,200
375,REPLUG: Retrieval-Augmented Black-Box Language Models,2024,188
63,Enhancing Retrieval-Augmented Large Language Models with Iterative Retrieval-Generation Synergy,2023,184
377,Enhancing Financial Sentiment Analysis via Retrieval Augmented Large Language Models,2023,178
24,"Improving large language model applications in biomedicine with retrieval-augmented generation: a systematic review, meta-analysis, and clinical d...",2025,177
5,Evaluation of Retrieval-Augmented Generation: A Survey,2025,169
18,Integrating Retrieval-Augmented Generation with Large Language Models in Nephrology: Advancing Practical Applications,2024,167
13,Retrieval-Augmented Generation with Knowledge Graphs for Customer Service Question Answering,2024,158
36,Applying generative AI with retrieval augmented generation to summarize and extract key clinical information from electronic health records,2024,153
10,LightRAG: Simple and Fast Retrieval-Augmented Generation,2025,153
30,Development of a liver disease–specific large language model chat interface using retrieval-augmented generation,2024,149
8,Evaluating Retrieval Quality in Retrieval-Augmented Generation,2024,148
9,Graph Retrieval-Augmented Generation: A Survey,2025,145
25,Retrieval augmented generation for 10 large language models and its generalizability in assessing medical fitness,2025,143
12,Interactive AI With Retrieval-Augmented Generation for Next Generation Networking,2024,140
224,Blended RAG: Improving RAG (Retriever-Augmented Generation) Accuracy with Semantic Search and Hybrid Query-Based Retrievers,2024,138
227,Hallucination Mitigation for Retrieval-Augmented Large Language Models: A Review,2025,133
19,Seven Failure Points When Engineering a Retrieval Augmented Generation System,2024,132
257,Improving medical reasoning through retrieval and self-reflection with retrieval-augmented large language models,2024,131
14,Retrieval-augmented generation for generative artificial intelligence in health care,2025,128
23,ARES: An Automated Evaluation Framework for Retrieval-Augmented Generation Systems,2024,127
98,Retrieval Augmented Code Generation and Summarization,2021,127
26,HybridRAG: Integrating Knowledge Graphs and Vector Retrieval Augmented Generation for Efficient Information Extraction,2024,124
35,Performance comparison of retrieval-augmented generation and fine-tuned large language models for construction safety management knowledge retrieval,2024,124
17,Retrieval-Augmented Generation (RAG) Chatbots for Education: A Survey of Applications,2025,124
16,Retrieval-augmented generation for educational application: A systematic survey,2025,122
11,Corrective Retrieval Augmented Generation,2025,117
830,MuRAG: Multimodal Retrieval-Augmented Generator for Open Question Answering over Images and Text,2022,116
20,Retrieval-Augmented Generation for AI-Generated Content: A Survey,2026,111
34,CBR-RAG: Case-Based Reasoning for Retrieval Augmented Generation in LLMs for Legal Question Answering,2024,110
32,MedRAG: Enhancing Retrieval-augmented Generation with Knowledge Graph-Elicited Reasoning for Healthcare Copilot,2025,109
22,Searching for Best Practices in Retrieval-Augmented Generation,2024,109
202,KRAGEN: a knowledge graph-enhanced RAG framework for biomedical problem solving using large language models,2024,107

In [14]:
import re


def classify_paper(title):
    title = str(title).lower()

    # --------------------------------------------------
    # 1. GRAPH RAG
    # --------------------------------------------------
    if (
        "graph rag" in title
        or "graph retrieval-augmented" in title
        or "knowledge graph" in title and "rag" in title
    ):
        return "GRAPH_RAG"

    # --------------------------------------------------
    # 2. MULTIMODAL RAG
    # --------------------------------------------------
    if (
        "multimodal rag" in title
        or "multimodal retrieval-augmented" in title
        or "retrieval-augmented" in title
        and "image" in title
    ):
        return "MULTIMODAL"

    # --------------------------------------------------
    # 3. AGENTIC / ADAPTIVE RAG
    # --------------------------------------------------
    if any(
    term in title
    for term in [
        "agentic rag",
        "agent rag",
        "adaptive-rag",
        "adaptive rag",
        "corrective retrieval augmented",
        "self-rag",
        "active retrieval augmented",
                ]
    ):
        return "AGENTIC"

    # --------------------------------------------------
    # 4. RAG EVALUATION
    # --------------------------------------------------
    if (
        "ragas" in title
        or (
            ("rag" in title or "retrieval-augmented" in title)
            and any(
                term in title
                for term in [
                    "evaluation",
                    "evaluating",
                    "benchmark",
                ]
            )
        )
    ):
        return "EVALUATION"

    # --------------------------------------------------
    # 5. CORE RAG
    # --------------------------------------------------
    if (
        "retrieval-augmented generation" in title
        or "retrieval augmented generation" in title
        or "retrieval-augmented language model" in title
        or "retrieval augmented language model" in title
        or " rag " in f" {title} "
    ):
        return "CORE_RAG"

    # --------------------------------------------------
    # 6. RETRIEVAL
    # --------------------------------------------------
    if any(
        term in title
        for term in [
            "dense retrieval",
            "information retrieval",
            "passage retrieval",
            "document retrieval",
            "neural retrieval",
            "retrieval model",
            "retrieval system",
            "retriever",
        ]
    ):
        return "RETRIEVAL"

    # --------------------------------------------------
    # 7. LLM
    # --------------------------------------------------
    if any(
        term in title
        for term in [
            "large language model",
            "large language models",
            "llm",
            "language model",
        ]
    ):
        return "LLM"

    # --------------------------------------------------
    # 8. BACKGROUND
    # --------------------------------------------------
    return "BACKGROUND"

In [15]:
df["paper_category"] = df["title"].apply(
    classify_paper
)

In [16]:
df["paper_category"].value_counts()

paper_category
CORE_RAG      401
LLM           200
GRAPH_RAG      97
BACKGROUND     95
AGENTIC        52
MULTIMODAL     52
EVALUATION     38
RETRIEVAL       9
Name: count, dtype: int64

In [17]:
for category in df["paper_category"].unique():

    print("\n" + "=" * 60)
    print(category)
    print("=" * 60)

    print(
        df.loc[
            df["paper_category"] == category,
            "title"
        ].head(15).to_string(index=False)
    )

============================================================
CORE_RAG
============================================================
                                                                                    Retrieval-Augmented Generation for Large Language Models: A Survey
                                     Improving the Domain Adaptation of Retrieval Augmented Generation (RAG) Models for Open Domain Question Answering
                                                           Retrieval augmented generation for large language models in healthcare: A systematic review
                                                                                              LightRAG: Simple and Fast Retrieval-Augmented Generation
                                                                     Interactive AI With Retrieval-Augmented Generation for Next Generation Networking
                                                          Retrieval-Augmented Generation with Knowledge Graphs for Customer Service Question Answering
                                                                  Retrieval-augmented generation for generative artificial intelligence in health care
           Optimization of hepatological clinical guidelines interpretation by large language models: a retrieval augmented generation-based framework
                                                                       Retrieval-augmented generation for educational application: A systematic survey
                                                                 Retrieval-Augmented Generation (RAG) Chatbots for Education: A Survey of Applications
                                 Integrating Retrieval-Augmented Generation with Large Language Models in Nephrology: Advancing Practical Applications
                                                                         Seven Failure Points When Engineering a Retrieval Augmented Generation System
                                                                                     Retrieval-Augmented Generation for AI-Generated Content: A Survey
                                                                                        Searching for Best Practices in Retrieval-Augmented Generation
Improving large language model applications in biomedicine with retrieval-augmented generation: a systematic review, meta-analysis, and clinical de...

============================================================
AGENTIC
============================================================
                                                                        Active Retrieval Augmented Generation
                                                                    Corrective Retrieval Augmented Generation
                                                                    Corrective Retrieval Augmented Generation
                                              Agentic Retrieval-Augmented Generation: A Survey on Agentic RAG
                                                                        Active Retrieval Augmented Generation
        Adaptive-RAG: Learning to Adapt Retrieval-Augmented Large Language Models through Question Complexity
        Adaptive-RAG: Learning to Adapt Retrieval-Augmented Large Language Models through Question Complexity
                                     Leveraging Agentic RAG to Reduce Hallucinations in Large Language Models
                      Agentic RAG for Software Testing with Hybrid Vector-Graph and Multi-Agent Orchestration
                                                                      Agentic RAG with Human-in-the-Retrieval
                                      CyberRAG: An agentic RAG cyber attack classification and reporting tool
                                          Sustainable Digitalization of Business with Multi-Agent RAG and LLM
          Towards Interpretable Radiology Report Generation via Concept Bottlenecks Using a Multi-agentic RAG
    Monitoring indoor environmental conditions in office buildings using a sustainable Agentic RAG-LLM system
MERMAIDS: Structured Memory and Evidence Reuse for Reducing Multi-Hop Retrieval Hallucinations in Agentic RAG

============================================================
EVALUATION
============================================================
                                                                   RAGAs: Automated Evaluation of Retrieval Augmented Generation
                                                            Benchmarking Large Language Models in Retrieval-Augmented Generation
                                                                        Benchmarking Retrieval-Augmented Generation for Medicine
                                                                          Evaluation of Retrieval-Augmented Generation: A Survey
                                                                  Evaluating Retrieval Quality in Retrieval-Augmented Generation
                                              ARES: An Automated Evaluation Framework for Retrieval-Augmented Generation Systems
                                  Design and Evaluation of a Retrieval-Augmented Generation Architecture for OWASP Security Data
                         CRUD-RAG: A Comprehensive Chinese Benchmark for Retrieval-Augmented Generation of Large Language Models
                                                            Benchmarking Large Language Models in Retrieval-Augmented Generation
         CyberMetric: A Benchmark Dataset based on Retrieval-Augmented Generation for Evaluating LLMs in Cybersecurity Knowledge
                                    Evaluating Retrieval-Augmented Generation Models for Financial Report Question and Answering
                                                                        Benchmarking Retrieval-Augmented Generation for Medicine
                                           FeB4RAG: Evaluating Federated Search in the Context of Retrieval Augmented Generation
Evaluation of the integration of retrieval-augmented generation in large language model for breast cancer nursing care responses
                                                 Performance Evaluation of Vector Embeddings with Retrieval-Augmented Generation

============================================================
GRAPH_RAG
============================================================
                                                                                            Graph Retrieval-Augmented Generation: A Survey
                                                                                                GRAG: Graph Retrieval-Augmented Generation
                    HybridRAG: Integrating Knowledge Graphs and Vector Retrieval Augmented Generation for Efficient Information Extraction
                           MedRAG: Enhancing Retrieval-augmented Generation with Knowledge Graph-Elicited Reasoning for Healthcare Copilot
                                                                  Graph Retrieval-Augmented Generation for Large Language Models: A Survey
                                                               Knowledge Graph Retrieval-Augmented Generation for LLM-based Recommendation
                                                                                            Graph Retrieval-Augmented Generation: A Survey
Document GraphRAG: Knowledge Graph Enhanced Retrieval Augmented Generation for Document Question Answering Within the Manufacturing Domain
                                   Medical Graph RAG: Evidence-based Medical Large Language Model via Graph Retrieval-Augmented Generation
                                                                  Graph Retrieval-Augmented Generation for Large Language Models: A Survey
                                     Medical Graph RAG: Towards Safe Medical Large Language Model via Graph Retrieval-Augmented Generation
                               KRAGEN: a knowledge graph-enhanced RAG framework for biomedical problem solving using large language models
                                          GNN-RAG: Graph Neural Retrieval for Efficient Large Language Model Reasoning on Knowledge Graphs
           RAG-based explainable prediction of road users behaviors for automated driving using knowledge graphs and large language models
                                          Graph RAG-based fault diagnosis for train bogies using knowledge graphs and large language model

============================================================
LLM
============================================================
                             Enhancing Retrieval-Augmented Large Language Models with Iterative Retrieval-Generation Synergy
           Affordance-Compiled Intelligence: Observable-Only Cognitive Impedance Matching for No-Meta LLM-Integrated Systems
                                                                                           A Survey of Large Language Models
                                     Open-RAG: Enhanced Retrieval Augmented Reasoning with Open-Source Large Language Models
                                 From RAGs to riches: Utilizing large language models to write documents for clinical trials
RAG-Driver: Generalisable Driving Explanations with Retrieval-Augmented In-Context Multi-Modal Large Language Model Learning
                   Astute RAG: Overcoming Imperfect Retrieval Augmentation and Knowledge Conflicts for Large Language Models
                                                                           A Comprehensive Overview of Large Language Models
                                                                              LaMDA: Language Models for Dialog Applications
                                      Leveraging RAG-Enhanced Large Language Model for Semi-Supervised Log Anomaly Detection
                 Generative AI Agents With Large Language Model for Satellite Networks via a Mixture of Experts Transmission
     RAGAR, Your Falsehood Radar: RAG-Augmented Reasoning for Political Fact-Checking using Multimodal Large Language Models
                                            Biomedical knowledge graph-optimized prompt generation for large language models
                           Exploring the capabilities and limitations of large language models in the electric energy sector
                                                                                             Large Language Models: A Survey

============================================================
BACKGROUND
============================================================
                                                              Retrieval Augmented Code Generation and Summarization
                                   RadioRAG: Online Retrieval–Augmented Generation for Radiology Question Answering
                                                                    A Survey on Retrieval-Augmented Text Generation
                                                  Generation-Augmented Retrieval for Open-Domain Question Answering
                                               Enriching Location Representation with Detailed Semantic Information
                             A survey on retrieval-augmentation generation (RAG) models for healthcare applications
            Pre-train, Prompt, and Predict: A Systematic Survey of Prompting Methods in Natural Language Processing
                                               SciPy 1.0: fundamental algorithms for scientific computing in Python
                                       Natural language processing: state of the art, current trends and challenges
                                          KET-RAG: A Cost-Efficient Multi-Granular Indexing Framework for Graph-RAG
                                 Leveraging Graph-RAG for Enhanced Diagnostic and Treatment Strategies in Dentistry
                                                      Superpixel Image Classification with Graph Attention Networks
                                         TigerVector: Supporting Vector Search in Graph Databases for Advanced RAGs
Global Discovery: A Global Graph-RAG Approach for Query-Focused Multimodal Summarization Across Multiple PDF Papers
                                  Medical Graph-RAG: Bilingual Graph-Based Reasoning for Cardiological Intelligence

============================================================
MULTIMODAL
============================================================
      Ask in Any Modality: A Comprehensive Survey on Multimodal Retrieval-Augmented Generation
                RULE: Reliable Multimodal RAG for Factuality in Medical Vision Language Models
     Re-ViLM: Retrieval-Augmented Visual Language Model for Zero and Few-Shot Image Captioning
     MMM-RAG: A Multi-Agent Multi-Feature Method for Multimodal Retrieval-Augmented Generation
    An Agentic, Multimodal RAG Framework for Risk-Aware Surgical Robotics User Manual Creation
                  MMed-RAG: Versatile Multimodal RAG System for Medical Vision Language Models
                          CoRe-MMRAG: Cross-Source Knowledge Reconciliation for Multimodal RAG
  A Comprehensive Survey on Multimodal RAG: All Combinations of Modalities as Input and Output
                    Multimodal RAG for Enhanced Information Retrieval and Generation in Retail
    FinRAGBench-V: A Benchmark for Multimodal RAG with Visual Citation in the Financial Domain
                            Enhanced Multimodal RAG-LLM for Accurate Visual Question Answering
                                                  Multimodal RAG Analysis of Product Datasheet
                   HierFinRAG—Hierarchical Multimodal RAG for Financial Document Understanding
                                      AMR-CSI: Adaptive Multimodal RAG for Cold Start Indexing
Structured Multimodal RAG: Document-Aware Retrieval and Alignment for Hallucination Mitigation

============================================================
RETRIEVAL
============================================================
                                                                        GNN-RAG: Graph Neural Retrieval for Large Language Model Reasoning
                                                                                 Large Language Models for Information Retrieval: A Survey
                                               RAG-IoE: IoT context-aware information retrieval with Large Language Models in Industry 5.0
                                                    Leveraging Passage Retrieval with Generative Models for Open Domain Question Answering
                                                                                Dense Passage Retrieval for Open-Domain Question Answering
                                                       Retrieval-Augmented Retrieval: Large Language Models are Strong Zero-Shot Retriever
                                                              Soft prompt tuning for augmenting dense retrieval with large language models
                                                                    SoccerRAG: Multimodal Soccer Information Retrieval via Natural Queries
SAMAC-R3-MED: Semantic alignment and multi-agent collaboration of retriever-reranker-responder models for multimodal engineering documents

In [18]:
print("Total papers:", len(df))

print(
    "Papers with abstracts:",
    df["abstract"].notna().sum()
)

print(
    "Papers without abstracts:",
    df["abstract"].isna().sum()
)

print(
    "Abstract coverage:",
    round(
        df["abstract"].notna().mean() * 100,
        2
    ),
    "%"
)

Total papers: 944
Papers with abstracts: 825
Papers without abstracts: 119
Abstract coverage: 87.39 %

In [19]:
df["abstract_length"] = (
    df["abstract"]
    .fillna("")
    .str.split()
    .str.len()
)

df["abstract_length"].describe()

count    944.000000
mean     156.686441
std       87.371218
min        0.000000
25%      118.750000
50%      173.000000
75%      210.250000
max      624.000000
Name: abstract_length, dtype: float64

In [20]:
title_duplicates = (
    df[
        df["title"].notna()
    ]
    .assign(
        title_normalized=lambda x:
        x["title"]
        .str.lower()
        .str.replace(
            r"[^a-z0-9]+",
            " ",
            regex=True
        )
        .str.strip()
    )
)

duplicates = title_duplicates[
    title_duplicates["title_normalized"].duplicated(
        keep=False
    )
].sort_values("title_normalized")

duplicates[
    [
        "title",
        "paper_id",
        "doi",
        "year",
        "citation_count"
    ]
].head(50)

,title,paper_id,doi,year,citation_count
715,A Survey of Personalization: From RAG to Agent,https://openalex.org/W4415160040,https://doi.org/10.48550/arxiv.2504.10147,2025,2
744,A Survey of Personalization: From RAG to Agent,https://openalex.org/W7147234952,https://doi.org/10.1145/3802586,2026,1
280,"A Survey on Hallucination in Large Language Models: Principles, Taxonomy, Challenges, and Open Questions",https://openalex.org/W4388585881,https://doi.org/10.48550/arxiv.2311.05232,2023,218
379,"A Survey on Hallucination in Large Language Models: Principles, Taxonomy, Challenges, and Open Questions",https://openalex.org/W4404534210,https://doi.org/10.1145/3703155,2024,2111
96,A Survey on RAG Meeting LLMs: Towards Retrieval-Augmented Large Language Models,https://openalex.org/W4401857375,https://doi.org/10.1145/3637528.3671470,2024,757
216,A Survey on RAG Meeting LLMs: Towards Retrieval-Augmented Large Language Models,https://openalex.org/W4396882099,https://doi.org/10.48550/arxiv.2405.06211,2024,15
1,Active Retrieval Augmented Generation,https://openalex.org/W4389519118,https://doi.org/10.18653/v1/2023.emnlp-main.495,2023,454
102,Active Retrieval Augmented Generation,https://openalex.org/W4376312546,https://doi.org/10.48550/arxiv.2305.06983,2023,18
200,Adaptive-RAG: Learning to Adapt Retrieval-Augmented Large Language Models through Question Complexity,https://openalex.org/W4401042753,https://doi.org/10.18653/v1/2024.naacl-long.389,2024,218
248,Adaptive-RAG: Learning to Adapt Retrieval-Augmented Large Language Models through Question Complexity,https://openalex.org/W4393119012,https://doi.org/10.48550/arxiv.2403.14403,2024,11
504,Advanced RAG Models with Graph Structures: Optimizing Complex Knowledge Reasoning and Text Generation,https://openalex.org/W4405845669,https://doi.org/10.1109/isceic63613.2024.10810209,2024,25
618,Advanced RAG Models with Graph Structures: Optimizing Complex Knowledge Reasoning and Text Generation,https://openalex.org/W4404354814,https://doi.org/10.48550/arxiv.2411.03572,2024,1
679,Agentic RAG-Driven Multi-Omics Analysis for PI3K/AKT Pathway Deregulation in Precision Medicine,https://openalex.org/W4413930158,https://doi.org/10.3390/a18090545,2025,2
699,Agentic RAG-Driven Multi-Omics Analysis for PI3K/AKT Pathway Deregulation in Precision Medicine,https://openalex.org/W4412502352,https://doi.org/10.20944/preprints202507.1354.v1,2025,1
668,"AI Agents vs. Agentic AI: A Conceptual taxonomy, applications and challenges",https://openalex.org/W4413427262,https://doi.org/10.1016/j.inffus.2025.103599,2025,238
681,"AI Agents vs. Agentic AI: A Conceptual Taxonomy, Applications and Challenges",https://openalex.org/W4412505619,https://doi.org/10.70777/si.v2i3.15161,2025,175
256,Almanac — Retrieval-Augmented Language Models for Clinical Medicine,https://openalex.org/W4391221150,https://doi.org/10.1056/aioa2300068,2024,401
372,Almanac: Retrieval-Augmented Language Models for Clinical Medicine,https://openalex.org/W4367672504,https://doi.org/10.21203/rs.3.rs-2883198/v1,2023,43
376,Almanac: Retrieval-Augmented Language Models for Clinical Medicine,https://openalex.org/W4323076364,https://doi.org/10.48550/arxiv.2303.01229,2023,28
496,AMSnet-KG: A Netlist Dataset for LLM-based AMS Circuit Auto-design Using Knowledge Graph RAG,https://openalex.org/W4410683950,https://doi.org/10.1145/3736166,2025,17
547,AMSnet-KG: A Netlist Dataset for LLM-based AMS Circuit Auto-Design Using Knowledge Graph RAG,https://openalex.org/W4404649752,https://doi.org/10.48550/arxiv.2411.13560,2024,1
726,An Agent-Based RAG Architecture for Intelligent Tourism Assistance: The Valencia Case Study,https://openalex.org/W4417041577,https://doi.org/10.3390/tourhosp6050266,2025,3
771,An Agent-Based RAG Architecture for Intelligent Tourism Assistance: The Valencia Case Study,https://openalex.org/W4416231572,https://doi.org/10.20944/preprints202511.0576.v1,2025,1
717,"Anchoring Global Security: Autonomous Shipping with Mind Reading AI, GPT-core and MAMBA- core Agents, RAG-Fusion, AI Communities, Hive- AI, and th...",https://openalex.org/W4405994976,https://doi.org/10.55277/researchhub.nl5249y9,2025,2
740,"Anchoring Global Security: Autonomous Shipping with Mind Reading AI, GPT-core and MAMBA- core Agents, RAG-Fusion, AI Communities, Hive- AI, and th...",https://openalex.org/W4406206613,https://doi.org/10.55277/researchhub.nl5249y9.1,2025,1
108,Ask in Any Modality: A Comprehensive Survey on Multimodal Retrieval-Augmented Generation,https://openalex.org/W4412887933,https://doi.org/10.18653/v1/2025.findings-acl.861,2025,40
867,Ask in Any Modality: A Comprehensive Survey on Multimodal Retrieval-Augmented Generation,https://openalex.org/W4407571030,https://doi.org/10.48550/arxiv.2502.08826,2025,2
3,Benchmarking Large Language Models in Retrieval-Augmented Generation,https://openalex.org/W4393147129,https://doi.org/10.1609/aaai.v38i16.29728,2024,382
48,Benchmarking Large Language Models in Retrieval-Augmented Generation,https://openalex.org/W4386556635,https://doi.org/10.48550/arxiv.2309.01431,2023,52
4,Benchmarking Retrieval-Augmented Generation for Medicine,https://openalex.org/W4402670290,https://doi.org/10.18653/v1/2024.findings-acl.372,2024,269
89,Benchmarking Retrieval-Augmented Generation for Medicine,https://openalex.org/W4392019609,https://doi.org/10.48550/arxiv.2402.13178,2024,24
371,Chain-of-Note: Enhancing Robustness in Retrieval-Augmented Language Models,https://openalex.org/W4404782899,https://doi.org/10.18653/v1/2024.emnlp-main.813,2024,46
395,Chain-of-Note: Enhancing Robustness in Retrieval-Augmented Language Models,https://openalex.org/W4388748510,https://doi.org/10.48550/arxiv.2311.09210,2023,8
794,Conceptualising RAG-Driven Agentic AI with Multi-Layer MCP for Seismic Structural Systems,https://openalex.org/W7133793116,https://doi.org/10.3390/buildings16051018,2026,1
796,Conceptualising RAG-Driven Agentic AI with Multi-Layer MCP for Seismic Structural Systems,https://openalex.org/W7110076166,https://doi.org/10.20944/preprints202512.0534.v1,2025,1
11,Corrective Retrieval Augmented Generation,https://openalex.org/W4410705984,https://doi.org/10.2139/ssrn.5267341,2025,117
59,Corrective Retrieval Augmented Generation,https://openalex.org/W4391418506,https://doi.org/10.48550/arxiv.2401.15884,2024,30
45,CRUD-RAG: A Comprehensive Chinese Benchmark for Retrieval-Augmented Generation of Large Language Models,https://openalex.org/W4403560390,https://doi.org/10.1145/3701228,2024,96
269,CRUD-RAG: A Comprehensive Chinese Benchmark for Retrieval-Augmented Generation of Large Language Models,https://openalex.org/W4391421370,https://doi.org/10.48550/arxiv.2401.17043,2024,7
733,Detecting Cloud Misconfigurations with RAG and Intelligent Agents: A Natural Language Understanding Approach,https://openalex.org/W4406620930,https://doi.org/10.52783/jes.7882,2025,4
749,Detecting Cloud Misconfigurations with RAG and Intelligent Agents: A Natural Language Understanding Approach,https://openalex.org/W4410800373,https://doi.org/10.2139/ssrn.5271734,2025,3
30,Development of a liver disease–specific large language model chat interface using retrieval-augmented generation,https://openalex.org/W4392544551,https://doi.org/10.1097/hep.0000000000000834,2024,149
123,Development of a Liver Disease-Specific Large Language Model Chat Interface using Retrieval Augmented Generation,https://openalex.org/W4388594005,https://doi.org/10.1101/2023.11.10.23298364,2023,42
575,DO-RAG: A Domain-Specific QA Framework Using Knowledge Graph-Enhanced Retrieval-Augmented Generation,https://openalex.org/W4410764243,https://doi.org/10.36227/techrxiv.174837976.69904638/v1,2025,3
634,DO-RAG: A Domain-Specific QA Framework Using Knowledge Graph-Enhanced Retrieval-Augmented Generation,https://openalex.org/W4410576482,https://doi.org/10.1007/978-981-95-7394-3_28,2026,1
635,DO-RAG: A Domain-Specific QA Framework using Knowledge Graph-Enhanced Retrieval-Augmented Generation,https://openalex.org/W4411491672,https://doi.org/10.2139/ssrn.5259088,2025,1
677,Emotional RAG: Enhancing Role-Playing Agents through Emotional Retrieval,https://openalex.org/W4407736938,https://doi.org/10.1109/ickg63256.2024.00023,2024,14
769,Emotional RAG: Enhancing Role-Playing Agents through Emotional Retrieval,https://openalex.org/W4404343018,https://doi.org/10.48550/arxiv.2410.23041,2024,1
380,Enhancing Noise Robustness of Retrieval-Augmented Language Models with Adaptive Adversarial Training,https://openalex.org/W4402671700,https://doi.org/10.18653/v1/2024.acl-long.540,2024,28
477,Enhancing Noise Robustness of Retrieval-Augmented Language Models with Adaptive Adversarial Training,https://openalex.org/W4399317906,https://doi.org/10.48550/arxiv.2405.20978,2024,2

In [21]:
# Number of unique normalized titles
unique_titles = title_duplicates["title_normalized"].nunique()

# Number of records that belong to duplicated-title groups
duplicate_records = title_duplicates[
    title_duplicates["title_normalized"].duplicated(keep=False)
]

print("Total records:", len(df))
print("Unique normalized titles:", unique_titles)
print("Records in duplicate-title groups:", len(duplicate_records))
print(
    "Potential duplicate records:",
    len(duplicate_records) - duplicate_records["title_normalized"].nunique()
)

Total records: 944
Unique normalized titles: 876
Records in duplicate-title groups: 132
Potential duplicate records: 68

In [22]:
duplicate_groups = (
    title_duplicates[
        title_duplicates["title_normalized"].duplicated(
            keep=False
        )
    ]
    .sort_values(
        ["title_normalized", "citation_count"],
        ascending=[True, False]
    )
)

duplicate_groups[
    [
        "title",
        "doi",
        "year",
        "citation_count"
    ]
].head(50)

,title,doi,year,citation_count
715,A Survey of Personalization: From RAG to Agent,https://doi.org/10.48550/arxiv.2504.10147,2025,2
744,A Survey of Personalization: From RAG to Agent,https://doi.org/10.1145/3802586,2026,1
379,"A Survey on Hallucination in Large Language Models: Principles, Taxonomy, Challenges, and Open Questions",https://doi.org/10.1145/3703155,2024,2111
280,"A Survey on Hallucination in Large Language Models: Principles, Taxonomy, Challenges, and Open Questions",https://doi.org/10.48550/arxiv.2311.05232,2023,218
96,A Survey on RAG Meeting LLMs: Towards Retrieval-Augmented Large Language Models,https://doi.org/10.1145/3637528.3671470,2024,757
216,A Survey on RAG Meeting LLMs: Towards Retrieval-Augmented Large Language Models,https://doi.org/10.48550/arxiv.2405.06211,2024,15
1,Active Retrieval Augmented Generation,https://doi.org/10.18653/v1/2023.emnlp-main.495,2023,454
102,Active Retrieval Augmented Generation,https://doi.org/10.48550/arxiv.2305.06983,2023,18
200,Adaptive-RAG: Learning to Adapt Retrieval-Augmented Large Language Models through Question Complexity,https://doi.org/10.18653/v1/2024.naacl-long.389,2024,218
248,Adaptive-RAG: Learning to Adapt Retrieval-Augmented Large Language Models through Question Complexity,https://doi.org/10.48550/arxiv.2403.14403,2024,11
504,Advanced RAG Models with Graph Structures: Optimizing Complex Knowledge Reasoning and Text Generation,https://doi.org/10.1109/isceic63613.2024.10810209,2024,25
618,Advanced RAG Models with Graph Structures: Optimizing Complex Knowledge Reasoning and Text Generation,https://doi.org/10.48550/arxiv.2411.03572,2024,1
679,Agentic RAG-Driven Multi-Omics Analysis for PI3K/AKT Pathway Deregulation in Precision Medicine,https://doi.org/10.3390/a18090545,2025,2
699,Agentic RAG-Driven Multi-Omics Analysis for PI3K/AKT Pathway Deregulation in Precision Medicine,https://doi.org/10.20944/preprints202507.1354.v1,2025,1
668,"AI Agents vs. Agentic AI: A Conceptual taxonomy, applications and challenges",https://doi.org/10.1016/j.inffus.2025.103599,2025,238
681,"AI Agents vs. Agentic AI: A Conceptual Taxonomy, Applications and Challenges",https://doi.org/10.70777/si.v2i3.15161,2025,175
256,Almanac — Retrieval-Augmented Language Models for Clinical Medicine,https://doi.org/10.1056/aioa2300068,2024,401
372,Almanac: Retrieval-Augmented Language Models for Clinical Medicine,https://doi.org/10.21203/rs.3.rs-2883198/v1,2023,43
376,Almanac: Retrieval-Augmented Language Models for Clinical Medicine,https://doi.org/10.48550/arxiv.2303.01229,2023,28
496,AMSnet-KG: A Netlist Dataset for LLM-based AMS Circuit Auto-design Using Knowledge Graph RAG,https://doi.org/10.1145/3736166,2025,17
547,AMSnet-KG: A Netlist Dataset for LLM-based AMS Circuit Auto-Design Using Knowledge Graph RAG,https://doi.org/10.48550/arxiv.2411.13560,2024,1
726,An Agent-Based RAG Architecture for Intelligent Tourism Assistance: The Valencia Case Study,https://doi.org/10.3390/tourhosp6050266,2025,3
771,An Agent-Based RAG Architecture for Intelligent Tourism Assistance: The Valencia Case Study,https://doi.org/10.20944/preprints202511.0576.v1,2025,1
717,"Anchoring Global Security: Autonomous Shipping with Mind Reading AI, GPT-core and MAMBA- core Agents, RAG-Fusion, AI Communities, Hive- AI, and th...",https://doi.org/10.55277/researchhub.nl5249y9,2025,2
740,"Anchoring Global Security: Autonomous Shipping with Mind Reading AI, GPT-core and MAMBA- core Agents, RAG-Fusion, AI Communities, Hive- AI, and th...",https://doi.org/10.55277/researchhub.nl5249y9.1,2025,1
108,Ask in Any Modality: A Comprehensive Survey on Multimodal Retrieval-Augmented Generation,https://doi.org/10.18653/v1/2025.findings-acl.861,2025,40
867,Ask in Any Modality: A Comprehensive Survey on Multimodal Retrieval-Augmented Generation,https://doi.org/10.48550/arxiv.2502.08826,2025,2
3,Benchmarking Large Language Models in Retrieval-Augmented Generation,https://doi.org/10.1609/aaai.v38i16.29728,2024,382
48,Benchmarking Large Language Models in Retrieval-Augmented Generation,https://doi.org/10.48550/arxiv.2309.01431,2023,52
4,Benchmarking Retrieval-Augmented Generation for Medicine,https://doi.org/10.18653/v1/2024.findings-acl.372,2024,269
89,Benchmarking Retrieval-Augmented Generation for Medicine,https://doi.org/10.48550/arxiv.2402.13178,2024,24
371,Chain-of-Note: Enhancing Robustness in Retrieval-Augmented Language Models,https://doi.org/10.18653/v1/2024.emnlp-main.813,2024,46
395,Chain-of-Note: Enhancing Robustness in Retrieval-Augmented Language Models,https://doi.org/10.48550/arxiv.2311.09210,2023,8
794,Conceptualising RAG-Driven Agentic AI with Multi-Layer MCP for Seismic Structural Systems,https://doi.org/10.3390/buildings16051018,2026,1
796,Conceptualising RAG-Driven Agentic AI with Multi-Layer MCP for Seismic Structural Systems,https://doi.org/10.20944/preprints202512.0534.v1,2025,1
11,Corrective Retrieval Augmented Generation,https://doi.org/10.2139/ssrn.5267341,2025,117
59,Corrective Retrieval Augmented Generation,https://doi.org/10.48550/arxiv.2401.15884,2024,30
45,CRUD-RAG: A Comprehensive Chinese Benchmark for Retrieval-Augmented Generation of Large Language Models,https://doi.org/10.1145/3701228,2024,96
269,CRUD-RAG: A Comprehensive Chinese Benchmark for Retrieval-Augmented Generation of Large Language Models,https://doi.org/10.48550/arxiv.2401.17043,2024,7
733,Detecting Cloud Misconfigurations with RAG and Intelligent Agents: A Natural Language Understanding Approach,https://doi.org/10.52783/jes.7882,2025,4
749,Detecting Cloud Misconfigurations with RAG and Intelligent Agents: A Natural Language Understanding Approach,https://doi.org/10.2139/ssrn.5271734,2025,3
30,Development of a liver disease–specific large language model chat interface using retrieval-augmented generation,https://doi.org/10.1097/hep.0000000000000834,2024,149
123,Development of a Liver Disease-Specific Large Language Model Chat Interface using Retrieval Augmented Generation,https://doi.org/10.1101/2023.11.10.23298364,2023,42
575,DO-RAG: A Domain-Specific QA Framework Using Knowledge Graph-Enhanced Retrieval-Augmented Generation,https://doi.org/10.36227/techrxiv.174837976.69904638/v1,2025,3
634,DO-RAG: A Domain-Specific QA Framework Using Knowledge Graph-Enhanced Retrieval-Augmented Generation,https://doi.org/10.1007/978-981-95-7394-3_28,2026,1
635,DO-RAG: A Domain-Specific QA Framework using Knowledge Graph-Enhanced Retrieval-Augmented Generation,https://doi.org/10.2139/ssrn.5259088,2025,1
677,Emotional RAG: Enhancing Role-Playing Agents through Emotional Retrieval,https://doi.org/10.1109/ickg63256.2024.00023,2024,14
769,Emotional RAG: Enhancing Role-Playing Agents through Emotional Retrieval,https://doi.org/10.48550/arxiv.2410.23041,2024,1
380,Enhancing Noise Robustness of Retrieval-Augmented Language Models with Adaptive Adversarial Training,https://doi.org/10.18653/v1/2024.acl-long.540,2024,28
477,Enhancing Noise Robustness of Retrieval-Augmented Language Models with Adaptive Adversarial Training,https://doi.org/10.48550/arxiv.2405.20978,2024,2

In [24]:
# Rank records within each normalized-title group
# Higher citation count = preferred canonical record

df_clean = (
    title_duplicates
    .sort_values(
        ["title_normalized", "citation_count"],
        ascending=[True, False]
    )
    .drop_duplicates(
        subset="title_normalized",
        keep="first"
    )
    .copy()
)

print("Original records:", len(df))
print("Clean records:", len(df_clean))
print("Records removed:", len(df) - len(df_clean))

Original records: 944
Clean records: 876
Records removed: 68

In [25]:
removed_records = df.loc[
    ~df["paper_id"].isin(df_clean["paper_id"])
].copy()

removed_records[
    [
        "title",
        "paper_id",
        "doi",
        "year",
        "citation_count"
    ]
].sort_values(
    "title"
).head(68)

,title,paper_id,doi,year,citation_count
744,A Survey of Personalization: From RAG to Agent,https://openalex.org/W7147234952,https://doi.org/10.1145/3802586,2026,1
280,"A Survey on Hallucination in Large Language Models: Principles, Taxonomy, Challenges, and Open Questions",https://openalex.org/W4388585881,https://doi.org/10.48550/arxiv.2311.05232,2023,218
216,A Survey on RAG Meeting LLMs: Towards Retrieval-Augmented Large Language Models,https://openalex.org/W4396882099,https://doi.org/10.48550/arxiv.2405.06211,2024,15
681,"AI Agents vs. Agentic AI: A Conceptual Taxonomy, Applications and Challenges",https://openalex.org/W4412505619,https://doi.org/10.70777/si.v2i3.15161,2025,175
547,AMSnet-KG: A Netlist Dataset for LLM-based AMS Circuit Auto-Design Using Knowledge Graph RAG,https://openalex.org/W4404649752,https://doi.org/10.48550/arxiv.2411.13560,2024,1
...,...,...,...,...,...
674,Traditional RAG vs. Agentic RAG: A Comparative Study of Retrieval-Augmented Systems,https://openalex.org/W7140314129,https://doi.org/10.1109/fmlds67896.2025.00073,2025,1
455,Tug-of-War Between Knowledge: Exploring and Resolving Knowledge Conflicts in Retrieval-Augmented Language Models,https://openalex.org/W4392120736,https://doi.org/10.48550/arxiv.2402.14409,2024,3
924,Youtube Multimodal Rag System,https://openalex.org/W7159825397,https://doi.org/10.5281/zenodo.19972012,2026,0
912,workinewgebrie/advanced-multimodal-rag-system: advanced-multimodal-rag-system,https://openalex.org/W7148276744,https://doi.org/10.5281/zenodo.19384371,2026,0
285,🧜Siren’s Song in the AI Ocean: A Survey on Hallucination in Large Language Models,https://openalex.org/W4412158322,https://doi.org/10.1162/coli.a.16,2025,233

In [30]:
removed_records = title_duplicates.loc[
    ~title_duplicates["paper_id"].isin(df_clean["paper_id"])
].copy()

removed_records.groupby("title_normalized").agg(
    records=("paper_id", "count"),
    years=("year", lambda x: sorted(x.tolist())),
    citations=("citation_count", lambda x: sorted(x.tolist(), reverse=True))
).sort_values("records", ascending=False)

,records,years,citations
title_normalized,,,
almanac retrieval augmented language models for clinical medicine,2,"[2023, 2023]","[43, 28]"
rag and rau a survey on retrieval augmented language model in natural language processing,2,"[2024, 2024]","[8, 4]"
do rag a domain specific qa framework using knowledge graph enhanced retrieval augmented generation,2,"[2025, 2026]","[1, 1]"
kaqg a knowledge graph enhanced rag for difficulty controlled question generation,2,"[2025, 2025]","[2, 1]"
logicscore transferability to multimodal rag systems with textual and visual data,1,[2026],[0]
...,...,...,...
graph retrieval augmented generation for large language models a survey,1,[2024],[22]
hm rag hierarchical multi agent multimodal retrieval augmented generation,1,[2025],[1]
how to build an adaptive ai tutor for any course using knowledge graph enhanced retrieval augmented generation kg rag,1,[2023],[12]
improving retrieval augmented language model with self reasoning,1,[2024],[2]
youtube multimodal rag system,1,[2026],[0]

In [33]:
duplicate_groups = title_duplicates[
    title_duplicates["title_normalized"].isin(
        removed_records["title_normalized"]
    )
].sort_values(
    ["title_normalized", "citation_count"],
    ascending=[True, False]
)

duplicate_groups[
    [
        "title",
        "title_normalized",
        "paper_id",
        "doi",
        "year",
        "citation_count"
    ]
]

,title,title_normalized,paper_id,doi,year,citation_count
715,A Survey of Personalization: From RAG to Agent,a survey of personalization from rag to agent,https://openalex.org/W4415160040,https://doi.org/10.48550/arxiv.2504.10147,2025,2
744,A Survey of Personalization: From RAG to Agent,a survey of personalization from rag to agent,https://openalex.org/W7147234952,https://doi.org/10.1145/3802586,2026,1
379,"A Survey on Hallucination in Large Language Models: Principles, Taxonomy, Challenges, and Open Questions",a survey on hallucination in large language models principles taxonomy challenges and open questions,https://openalex.org/W4404534210,https://doi.org/10.1145/3703155,2024,2111
280,"A Survey on Hallucination in Large Language Models: Principles, Taxonomy, Challenges, and Open Questions",a survey on hallucination in large language models principles taxonomy challenges and open questions,https://openalex.org/W4388585881,https://doi.org/10.48550/arxiv.2311.05232,2023,218
96,A Survey on RAG Meeting LLMs: Towards Retrieval-Augmented Large Language Models,a survey on rag meeting llms towards retrieval augmented large language models,https://openalex.org/W4401857375,https://doi.org/10.1145/3637528.3671470,2024,757
...,...,...,...,...,...,...
455,Tug-of-War Between Knowledge: Exploring and Resolving Knowledge Conflicts in Retrieval-Augmented Language Models,tug of war between knowledge exploring and resolving knowledge conflicts in retrieval augmented language models,https://openalex.org/W4392120736,https://doi.org/10.48550/arxiv.2402.14409,2024,3
908,workinewgebrie/advanced-multimodal-rag-system: advanced-multimodal-rag-system,workinewgebrie advanced multimodal rag system advanced multimodal rag system,https://openalex.org/W7148280897,https://doi.org/10.5281/zenodo.19384370,2026,0
912,workinewgebrie/advanced-multimodal-rag-system: advanced-multimodal-rag-system,workinewgebrie advanced multimodal rag system advanced multimodal rag system,https://openalex.org/W7148276744,https://doi.org/10.5281/zenodo.19384371,2026,0
923,Youtube Multimodal Rag System,youtube multimodal rag system,https://openalex.org/W7159804412,https://doi.org/10.5281/zenodo.19972011,2026,0
924,Youtube Multimodal Rag System,youtube multimodal rag system,https://openalex.org/W7159825397,https://doi.org/10.5281/zenodo.19972012,2026,0

In [34]:
df_clean = (
    title_duplicates
    .sort_values(
        ["title_normalized", "citation_count", "year", "paper_id"],
        ascending=[True, False, False, True]
    )
    .drop_duplicates(
        subset="title_normalized",
        keep="first"
    )
    .copy()
)

print("Original records:", len(df))
print("Clean records:", len(df_clean))
print("Records removed:", len(df) - len(df_clean))

Original records: 944
Clean records: 876
Records removed: 68

In [35]:
print(df_clean["title_normalized"].duplicated().sum())

0

In [36]:
df_clean.to_parquet(
    "../data/processed/papers_clean.parquet",
    index=False
)

print("Clean dataset saved successfully.")
print("Shape:", df_clean.shape)

Clean dataset saved successfully.
Shape: (876, 18)